sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 040428
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tPo64eQpmDfubFfiALA
    accessKeySecret: IKZv8D1gsy9TGDsTpzYsK1f7CoiKnf
    bucketName: web-qrd-study-springboot
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
